import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { ContextBundle, AgentNorthConfig } from "../core/types.js";

export async function generateArchitectureDoc(
  rootDir: string,
  config: AgentNorthConfig,
  bundles: ContextBundle[],
): Promise<void> {
  const docsDir = join(rootDir, ".agentnorth", "docs");
  await mkdir(docsDir, { recursive: true });

  const content = renderArchitecture(config, bundles);
  await writeFile(join(docsDir, "ARCHITECTURE.md"), content, "utf-8");
}

function renderArchitecture(
  config: AgentNorthConfig,
  bundles: ContextBundle[],
): string {
  const lines: string[] = [];

  lines.push(`# ${config.project.name} — Architecture`);
  lines.push("");
  lines.push(`Auto-generated by AgentNorth. ${bundles.length} modules indexed.`);
  lines.push("");

  // Overview table
  lines.push("## Modules");
  lines.push("");
  lines.push("| Module | Files | LOC | Internal Deps | External Deps | Decisions |");
  lines.push("|--------|-------|-----|---------------|---------------|-----------|");

  for (const bundle of bundles) {
    const loc = bundle.files.reduce((s, f) => s + f.loc, 0);
    const intDeps = bundle.dependencies.internal.join(", ") || "—";
    const extDeps = bundle.dependencies.external.slice(0, 3).join(", ") || "—";
    lines.push(
      `| **${bundle.module}** | ${bundle.files.length} | ${loc} | ${intDeps} | ${extDeps} | ${bundle.decisions.length} |`,
    );
  }
  lines.push("");

  // Dependency graph (Mermaid)
  lines.push("## Dependency Graph");
  lines.push("");
  lines.push("```mermaid");
  lines.push("graph TD");
  for (const bundle of bundles) {
    const id = sanitizeMermaidId(bundle.module);
    lines.push(`  ${id}[${bundle.module}]`);
    for (const dep of bundle.dependencies.internal) {
      lines.push(`  ${id} --> ${sanitizeMermaidId(dep)}`);
    }
  }
  lines.push("```");
  lines.push("");

  // Stack info
  if (config.project.framework) {
    lines.push("## Stack");
    lines.push("");
    lines.push(`- **Framework:** ${config.project.framework}`);
    lines.push("");
  }

  // All decisions across modules
  const allDecisions = bundles.flatMap((b) => b.decisions);
  if (allDecisions.length > 0) {
    lines.push("## Architecture Decisions");
    lines.push("");
    lines.push("| ID | Title | Module | Status | Date |");
    lines.push("|----|-------|--------|--------|------|");
    for (const d of allDecisions) {
      lines.push(`| ${d.id} | ${d.title} | ${d.module} | ${d.status} | ${d.date} |`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function sanitizeMermaidId(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_");
}
